#ifndef CONSTANTS_H
#define CONSTANTS_H

// screen
#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 900
#define DANGER_ZONE 200

// player
#define RADIUS 20
#define MAX_ACCELERATION 0.4f
#define MAX_VELOCITY 5
#define TURRET_LENGTH 20
#define SHIP_SCALE 0.55f

// entity
#define WALL_BOUNCE -0.1

// bullet
#define BULLET_VELOCITY 0.8
#define BULLET_RADIUS 3
#define BULLET_SCALE 0.6f

// enemy
#define MAX_VELOCITY_ENEMY 3
#define MAX_ACCELERATION_ENEMY 0.4
#define EVADE_THRESHOLD 150
#define EVASION_MULTIPLIER 0.6
#define PURSUIT_THRESHOLD 1200
#define BRUTE_RADIUS 25
#define MAX_VELOCITY_BRUTE 1.5
#define MAX_VELOCITY_SPRINTER 5

// powerup
#define POWERUP_RADIUS 25

#endif